### ISSUE TITLE
data-confirm and data-method breaks IE7 (and other IEs?)

### ISSUE THREAD

**Issue by camelpunch** [epotocko/yui3-ujs#1]
IE7 doesn't support :not(), but it's used as a selector. Better to use a separate check within the called function?

**Comment by epotocko** [comment]
Change line 112 to include selector-css3 to fix the issue:
    YUI().use('node-base', 'node-event-delegate', 'selector-css3', 'io-form', 'rails-ujs', 'rails-event-bubble', function(Y) {

I will commit the change later today.  Thanks!

**Comment by camelpunch** [comment]
Thanks, should've thought of that. Does the trick!
